-- hive metastore
CREATE DATABASE metastore DEFAULT CHARACTER SET UTF8;

CREATE user '%MYSQL_HIVE_USERNAME%'@'localhost' IDENTIFIED BY '%MYSQL_HIVE_PASSWORD%';
GRANT ALL PRIVILEGES ON metastore.* TO '%MYSQL_HIVE_USERNAME%'@'localhost' WITH GRANT OPTION;

CREATE user '%MYSQL_HIVE_USERNAME%'@'%' IDENTIFIED BY '%MYSQL_HIVE_PASSWORD%';
GRANT ALL PRIVILEGES ON metastore.* TO '%MYSQL_HIVE_USERNAME%'@'%' WITH GRANT OPTION;

-- mysql 5.x
-- GRANT ALL PRIVILEGES ON metastore.* TO '%MYSQL_HIVE_USERNAME%'@'localhost' IDENTIFIED BY '%MYSQL_HIVE_PASSWORD%';
-- GRANT ALL PRIVILEGES ON metastore.* TO '%MYSQL_HIVE_USERNAME%'@'%' IDENTIFIED BY '%MYSQL_HIVE_PASSWORD%';

FLUSH PRIVILEGES;

-- recovery
-- for mysql 8.x
-- DROP DATABASE metastore;
-- DROP USER IF EXISTS '%MYSQL_HIVE_USERNAME%'@'localhost', '%MYSQL_HIVE_USERNAME%'@'%';
