-- for hangul comment
ALTER TABLE metastore.TABLE_PARAMS CHANGE COLUMN PARAM_VALUE PARAM_VALUE mediumtext CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL COMMENT '';
ALTER TABLE metastore.COLUMNS_V2 CHANGE COLUMN COMMENT COMMENT VARCHAR(256) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL COMMENT '';
ALTER TABLE metastore.DBS CHANGE COLUMN `DESC` `DESC` VARCHAR(4000) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL COMMENT '';
ALTER TABLE metastore.PARTITION_KEYS CHANGE COLUMN PKEY_COMMENT PKEY_COMMENT VARCHAR(4000) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL COMMENT '';
